# Generated by Django 6.0.7 on 2026-07-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used', models.DecimalField(decimal_places=2, max_digits=5)),
                ('distance_miles', models.DecimalField(decimal_places=2, max_digits=10)),
                ('driving_hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_elapsed_hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel_stops', models.PositiveIntegerField(default=0)),
                ('rest_periods', models.PositiveIntegerField(default=0)),
                ('eld_log_days', models.PositiveIntegerField(default=0)),
                ('request_payload', models.JSONField(default=dict)),
                ('response_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
